language: ruby

env:
  global:
    - DISCOURSE_HOSTNAME=www.example.com

dist: trusty

cache: bundler --path $TRAVIS_BUILD_DIR/discourse/vendor

addons:
  postgresql: 9.6
  apt:
    packages:
    - gifsicle
    - jpegoptim
    - optipng
    - jhead

rvm:
  - 2.6.3

services:
  - redis-server

before_install:
  - git clone https://github.com/discourse/discourse.git discourse
  - cd discourse

install:
  - touch config/stripe.yml
  - git clone $TRAVIS_BUILD_DIR plugins/discourse-donations --depth 50 --branch $TRAVIS_BRANCH

before_script:
  - gem install bundler
  - bundle install
  - bundle exec rake db:create db:migrate

script:
  - "bundle exec rake plugin:spec[discourse-donations]"
  - "MODULE='Acceptance: Discourse Donations' bundle exec rake qunit:test[20000]"
  - "MODULE='component:stripe-card' bundle exec rake qunit:test[20000]"
