plugins:
  discourse_subscriptions_enabled:
    default: false
  discourse_subscriptions_extra_nav_subscribe:
    default: false
    client: true
  discourse_subscriptions_public_key:
    default: ''
    client: true
  discourse_subscriptions_secret_key:
    default: ''
    client: false
  discourse_subscriptions_webhook_secret:
    default: ''
    client: false
  discourse_subscriptions_allow_payments:
    default: false
    client: true
  discourse_subscriptions_currency:
    client: true
    default: 'USD'
    type: enum
    choices:
      - AUD
      - CAD
      - EUR
      - GBP
      - USD
      - NZD
      - INR
