plugins:
  discourse_subscriptions_enabled:
    default: false
  discourse_subscriptions_extra_nav_subscribe:
    default: false
    client: true
  discourse_subscriptions_public_key:
    default: ''
    client: true
  discourse_subscriptions_secret_key:
    default: ''
    client: false
  discourse_subscriptions_webhook_secret:
    default: ''
    client: false
  discourse_subscriptions_currency:
    client: true
    default: "USD"
    type: enum
    choices:
      - AUD
      - BRL
      - CAD
      - EUR
      - GBP
      - INR
      - NZD
      - USD
      - DKK
      - SGD
  discourse_subscriptions_campaign_enabled:
    client: true
    default: false
  discourse_subscriptions_campaign_goal:
    client: true
    default: 10
  discourse_subscriptions_campaign_type:
    client: true
    type: enum
    default: "Subscribers"
    choices:
      - Subscribers
      - Amount
  discourse_subscriptions_campaign_banner_location:
    client: true
    type: enum
    default: "Top"
    choices:
      - Top
      - Sidebar
  discourse_subscriptions_campaign_amount_raised:
    client: true
    default: 0
    hidden: true
  discourse_subscriptions_campaign_subscribers:
    client: true
    default: 0
    hidden: true
